"""Pydantic v2 schemas and models for Terra Odyssey API and Investigation Records.

All models strictly mirror schemas/investigation-record.schema.json,
schemas/analysis-result.schema.json, and the API contract specifications.
"""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


# --- RFC 9457 Problem Details ---

class ProblemDetails(BaseModel):
    """RFC 9457 compliant error structure."""
    model_config = ConfigDict(extra="allow")

    type: str = Field(
        default="about:blank",
        description="URI reference identifying the problem type"
    )
    title: str = Field(
        ...,
        description="Short, human-readable summary of the problem type"
    )
    status: int = Field(
        ...,
        description="HTTP status code generated by the origin server"
    )
    code: str = Field(
        ...,
        description="Machine-readable application error code"
    )
    detail: str = Field(
        ...,
        description="Human-readable explanation specific to this occurrence"
    )
    instance: Optional[str] = Field(
        default=None,
        description="URI reference that identifies the specific occurrence"
    )
    retryable: bool = Field(
        default=False,
        description="Whether the client may safely retry the request"
    )
    invalid_params: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description="Parameter-level validation issues if applicable"
    )


# --- Request Models ---

class UniversalQueryRequest(BaseModel):
    """Natural-language question submitted to the protected AI gateway."""
    model_config = ConfigDict(extra="forbid", strict=True)

    query: str = Field(
        ...,
        min_length=2,
        max_length=500,
        description="Question about Terra Odyssey data, methods, or workflows",
    )

    @field_validator("query", mode="before")
    @classmethod
    def normalize_query(cls, value: Any) -> Any:
        if isinstance(value, str):
            return value.strip()
        return value


class UniversalQueryResponse(BaseModel):
    """Normalized NVIDIA NIM answer returned to the web client."""
    model_config = ConfigDict(extra="forbid")

    answer: str
    model: str
    provider: Literal["NVIDIA NIM"] = "NVIDIA NIM"
    latency_ms: float = Field(..., ge=0)
    caveat: str


# --- Place search (geocoding) ---

class PlaceSearchResult(BaseModel):
    """A single normalized place returned by the geocoder."""
    model_config = ConfigDict(extra="forbid")

    id: str = Field(
        ...,
        min_length=1,
        max_length=120,
        description="Stable identifier from the upstream source (e.g. OSM type/id).",
    )
    name: str = Field(..., min_length=1, max_length=200)
    kind: str = Field(
        ...,
        description="Coarse feature kind: city, country, region, landmark, etc.",
    )
    country: Optional[str] = Field(default=None, max_length=80)
    admin1: Optional[str] = Field(
        default=None,
        max_length=120,
        description="First-order administrative division (state, region, province).",
    )
    longitude: float = Field(..., ge=-180.0, le=180.0)
    latitude: float = Field(..., ge=-90.0, le=90.0)
    bbox: tuple[float, float, float, float] = Field(
        ...,
        description="Bounding box as [minLon, minLat, maxLon, maxLat] in EPSG:4326.",
    )
    geojson: Optional[dict[str, Any]] = Field(
        default=None,
        description="Optional GeoJSON Polygon or MultiPolygon geometry representing the exact boundary.",
    )
    source: str = "nominatim"


class PlaceSearchResponse(BaseModel):
    """Normalized place-search response returned to the web client."""
    model_config = ConfigDict(extra="forbid")

    query: str = Field(..., min_length=1, max_length=120)
    results: List[PlaceSearchResult] = Field(default_factory=list)
    cached: bool = False

class PeriodRequest(BaseModel):
    """Temporal range specification in calendar years."""
    model_config = ConfigDict(extra="forbid", strict=True)

    start_year: int = Field(..., ge=1900, le=2100, description="Start year (inclusive)")
    end_year: int = Field(..., ge=1900, le=2100, description="End year (inclusive)")

    @model_validator(mode="after")
    def validate_year_order(self) -> PeriodRequest:
        if self.start_year > self.end_year:
            raise ValueError(
                f"start_year ({self.start_year}) must be less than or equal to end_year ({self.end_year})"
            )
        return self


def validate_region(v: Any) -> Any:
    """Validate that geometry is either a GeoJSON geometry dict or a 4-element bbox list."""
    if isinstance(v, (list, tuple)):
        if len(v) != 4:
            raise ValueError("Bounding box must contain exactly 4 coordinates: [min_lon, min_lat, max_lon, max_lat]")
        min_lon, min_lat, max_lon, max_lat = v
        if not all(isinstance(x, (int, float)) for x in (min_lon, min_lat, max_lon, max_lat)):
            raise ValueError("All bounding box coordinates must be numeric floats or integers")
        if not (-180.0 <= min_lon <= 180.0 and -180.0 <= max_lon <= 180.0):
            raise ValueError(f"Longitude coordinates out of bounds [-180, 180]: min_lon={min_lon}, max_lon={max_lon}")
        if not (-90.0 <= min_lat <= 90.0 and -90.0 <= max_lat <= 90.0):
            raise ValueError(f"Latitude coordinates out of bounds [-90, 90]: min_lat={min_lat}, max_lat={max_lat}")
        if min_lon >= max_lon:
            raise ValueError(f"min_lon ({min_lon}) must be strictly less than max_lon ({max_lon})")
        if min_lat >= max_lat:
            raise ValueError(f"min_lat ({min_lat}) must be strictly less than max_lat ({max_lat})")
        return [float(x) for x in v]
    elif isinstance(v, dict):
        geom_type = v.get("type")
        valid_types = {"Polygon", "MultiPolygon", "Point", "Feature", "FeatureCollection", "GeometryCollection"}
        if not geom_type or geom_type not in valid_types:
            raise ValueError(f"GeoJSON geometry type must be one of {valid_types}, got '{geom_type}'")
        if geom_type in {"Polygon", "MultiPolygon", "Point"} and "coordinates" not in v:
            raise ValueError(f"GeoJSON {geom_type} must contain 'coordinates'")
        return v
    else:
        raise ValueError("Region must be a GeoJSON geometry dictionary or a [min_lon, min_lat, max_lon, max_lat] bbox list")


class InvestigationRequest(BaseModel):
    """Request payload to create a new reproducible investigation job."""
    model_config = ConfigDict(extra="forbid")

    dataset_id: str = Field(..., min_length=1, description="Dataset identifier (e.g. 'D1', 'merra2_t2m', 'D2')")
    variable: str = Field(..., min_length=1, description="Target variable name (e.g. 'T2M', 'precipitationCal')")
    period: PeriodRequest = Field(..., description="Investigation time interval")
    region_a: Union[Dict[str, Any], List[float]] = Field(
        ...,
        description="Primary target region as GeoJSON geometry or [min_lon, min_lat, max_lon, max_lat] bbox"
    )
    region_b: Optional[Union[Dict[str, Any], List[float]]] = Field(
        default=None,
        description="Optional comparison region for paired contrast analysis"
    )
    temporal_aggregation: Literal["annual_mean", "annual_total", "seasonal"] = Field(
        default="annual_mean",
        description="Temporal summarization aggregation method"
    )
    spatial_aggregation: Literal["area_weighted"] = Field(
        default="area_weighted",
        description="Spatial aggregation method"
    )
    execution_mode: Literal["auto", "live", "cached_only", "demo_sample", "synthetic_test"] = Field(
        default="auto",
        description="Execution mode defining data acquisition behavior"
    )
    estimator_family: Literal["ols_hac"] = Field(
        default="ols_hac",
        description="Statistical trend estimator family"
    )
    selection_status: Literal["predefined", "exploratory_map_selected"] = Field(
        default="predefined",
        description="Whether regions were hypothesized a priori or selected from exploratory screening"
    )

    @field_validator("region_a", mode="after")
    @classmethod
    def check_region_a(cls, v: Any) -> Any:
        return validate_region(v)

    @field_validator("region_b", mode="after")
    @classmethod
    def check_region_b(cls, v: Any) -> Any:
        if v is not None:
            return validate_region(v)
        return v


# --- Job Status Models ---

JobStatusEnum = Literal["submitted", "running", "succeeded", "failed", "cancel_requested", "cancelled"]
StageEnum = Literal["validating", "acquiring", "normalizing", "aggregating", "analyzing", "publishing"]
ResultStatusEnum = Literal["supported", "inconclusive", "ineligible"]


class JobStatusResponse(BaseModel):
    """Operational status of an asynchronous investigation job."""
    model_config = ConfigDict(extra="ignore")

    job_id: str
    job_status: JobStatusEnum
    stage: StageEnum
    result_status: Optional[ResultStatusEnum] = None
    progress_pct: int = Field(default=0, ge=0, le=100)
    created_at: str
    started_at: Optional[str] = None
    completed_at: Optional[str] = None
    updated_at: Optional[str] = None
    error: Optional[Union[Dict[str, Any], str]] = None


# --- Catalog & Capability Models ---

class DatasetCapabilities(BaseModel):
    """Granular product and adapter capabilities."""
    model_config = ConfigDict(extra="allow")

    discoverable: bool = True
    previewable: bool = False
    series_supported: bool = False
    trend_supported: bool = False
    contrast_supported: bool = False
    badges: List[Literal["Browse", "View", "Analyze", "Compare"]] = Field(
        default_factory=lambda: ["Browse"]
    )
    unsupported_reason: Optional[str] = None


class DatasetCatalogItem(BaseModel):
    """Catalog metadata for an authoritative NASA dataset."""
    model_config = ConfigDict(extra="allow")

    dataset_id: str
    name: str
    collection: str
    version: str
    topic: str = "Atmosphere"
    provider: str = "NASA Earth Science"
    concept_id: Optional[str] = None
    native_resolution: Optional[str] = None
    license: Optional[str] = "NASA Open Data Policy"
    citation_doi: Optional[str] = None
    gibs_layer: Optional[str] = None
    source_type: str
    variable: str
    units: str
    spatial_support: str
    temporal_support: str
    coverage_start: str
    coverage_end: Optional[str] = None
    quality_policy: Dict[str, Any] = Field(default_factory=dict)
    provenance: Dict[str, Any] = Field(default_factory=dict)
    capabilities: DatasetCapabilities = Field(default_factory=DatasetCapabilities)
    categories: List[str] = Field(default_factory=list)
    supported_aggregations: List[str] = Field(default_factory=lambda: ["annual_mean", "annual_total", "seasonal"])
    supported_spatial_aggregations: List[str] = Field(default_factory=lambda: ["area_weighted"])


class AvailabilityGap(BaseModel):
    """Documented archive gap or mission transition window."""
    model_config = ConfigDict(extra="forbid")

    start_date: str
    end_date: str
    description: str


class EligibleSpan(BaseModel):
    """Contiguous period meeting the minimum >= 20 complete year requirement."""
    model_config = ConfigDict(extra="forbid")

    start_year: int
    end_year: int
    complete_years: int
    is_eligible: bool


class DatasetAvailabilityResponse(BaseModel):
    """Granule presence, archive timeline, and scientific trend eligibility."""
    model_config = ConfigDict(extra="allow")

    dataset_id: str
    name: str
    temporal_support: str
    coverage_start: str
    coverage_end: str
    total_years: int
    complete_years: int
    completeness_pct: float
    gaps: List[AvailabilityGap] = Field(default_factory=list)
    eligible_spans: List[EligibleSpan] = Field(default_factory=list)
    years_available: List[int] = Field(default_factory=list)
    gibs_layer: Optional[str] = None


class CatalogResponse(BaseModel):
    """Response containing reviewed datasets, defaults, and supported options."""
    model_config = ConfigDict(extra="ignore")

    datasets: Dict[str, DatasetCatalogItem]
    defaults: Dict[str, Any]
    supported_estimators: List[str]
    supported_aggregations: List[str]


class CapabilitiesResponse(BaseModel):
    """Capabilities and environment of the running Terra Odyssey instance."""
    model_config = ConfigDict(extra="ignore")

    execution_modes: List[str]
    system_version: str
    environment: Dict[str, Any]
    cached_granules: Dict[str, Any]


# --- Structured Map Models ---

class GridMetadata(BaseModel):
    """Grid coordinate definition for structured delivery."""
    model_config = ConfigDict(extra="allow")

    crs: str = "EPSG:4326"
    width: int
    height: int
    longitude: List[float]
    latitude: List[float]
    order: str = "latitude_longitude"


class LegendMetadata(BaseModel):
    """Legend scale and multiple testing metadata for the grid map."""
    model_config = ConfigDict(extra="allow")

    variable: str
    units: str
    center: float = 0.0
    minimum: float
    maximum: float
    fdr_method: str = "fdr_by"
    fdr_level: float = 0.05


class MapProvenance(BaseModel):
    """Provenance for multiple testing family and analysis footprint."""
    model_config = ConfigDict(extra="allow")

    map_family_id: str
    family_size: int


class MapBands(BaseModel):
    """Frozen 9 diagnostic bands contract for gridded trend field delivery."""
    model_config = ConfigDict(extra="allow")

    slope_per_decade: List[Optional[float]]
    slope_se_per_decade: List[Optional[float]] = Field(default_factory=list)
    ci_lower_per_decade: List[Optional[float]] = Field(default_factory=list)
    ci_upper_per_decade: List[Optional[float]] = Field(default_factory=list)
    raw_p_value: List[Optional[float]] = Field(default_factory=list)
    adjusted_p_value: List[Optional[float]] = Field(default_factory=list)
    coverage_fraction: List[Optional[float]] = Field(default_factory=list)
    eligibility_code: List[str] = Field(default_factory=list)
    evidence_code: List[str] = Field(default_factory=list)


class StructuredGridMapResponse(BaseModel):
    """Compressed 2D gridded trend field delivery schema."""
    model_config = ConfigDict(extra="ignore")

    grid: GridMetadata
    bands: Union[MapBands, Dict[str, List[Any]]]
    legend: LegendMetadata
    provenance: MapProvenance


# --- Paired Contrast & Evidence Models ---

class PairedContrastSummary(BaseModel):
    """Summary of paired regional difference contrast test."""
    model_config = ConfigDict(extra="allow")

    contrast_slope: float
    contrast_ci_95: List[float]
    contrast_p_value: float
    contrast_status: str
    region_a_slope: Optional[float] = None
    region_b_slope: Optional[float] = None
    units: str
    evidence_text: str


class EvidencePayload(BaseModel):
    """Evidence payload returned by /api/investigations/{job_id}/evidence."""
    model_config = ConfigDict(extra="allow")

    job_id: str
    result_status: Optional[str] = None
    results: List[Dict[str, Any]]
    contrast: Optional[PairedContrastSummary] = None
    headline_text: Optional[str] = None
    summary_stats: Optional[Dict[str, Any]] = None


# --- Complete Investigation Record Models ---

class ArtifactItem(BaseModel):
    """Checksum and metadata for an immutable investigation artifact."""
    checksum_sha256: str
    mime_type: str
    byte_size: int = Field(..., ge=0)


class SoftwareMetadata(BaseModel):
    """Execution environment and version metadata."""
    version: str
    environment: Dict[str, Any]
    git_commit: Optional[str] = None


class InvestigationRecordModel(BaseModel):
    """Pydantic model representing a complete frozen InvestigationRecord."""
    model_config = ConfigDict(extra="forbid")

    schema_version: str = "1.0.0"
    investigation_id: str
    created_at: str
    published_at: str
    job: Dict[str, Any]
    data_mode: Literal["live", "cached_verified", "demo_sample", "synthetic_test"]
    request: Dict[str, Any]
    resolved_configuration: Dict[str, Any]
    resolved_configuration_hash: str
    source_manifests: List[str]
    source_manifest_objects: List[Dict[str, Any]]
    results: List[Dict[str, Any]]
    artifact_index: Dict[str, ArtifactItem]
    record_hash: str
    map_family_id: Optional[str] = None
    software: SoftwareMetadata
    selection_history: List[Dict[str, Any]] = Field(default_factory=list)
    citations: List[str] = Field(default_factory=list)


# --- Study Plot Persistence Models (SQLite) ---

class StudyPlotCreate(BaseModel):
    """Payload to create or update a persistent study region plot in SQLite."""
    model_config = ConfigDict(extra="ignore")

    plot_id: Optional[str] = Field(
        default=None,
        description="Unique identifier for the plot; generated if omitted"
    )
    name: str = Field(
        default="Custom Study Region",
        description="Human-readable name or label for the study region"
    )
    is_active: bool = Field(
        default=True,
        description="Whether this plot is currently the active region"
    )
    geometry_type: str = Field(
        default="Polygon",
        description="GeoJSON geometry type (Polygon, LineString, etc.)"
    )
    coordinates: List[Any] = Field(
        ...,
        description="GeoJSON coordinates array"
    )
    bbox: List[float] = Field(
        ...,
        min_length=4,
        max_length=4,
        description="Bounding box [minLon, minLat, maxLon, maxLat]"
    )
    measurements: Dict[str, Any] = Field(
        default_factory=dict,
        description="Geodesic measurements: areaKm2, areaHa, perimeterKm, centroid, bounds"
    )
    dataset_id: Optional[str] = Field(
        default=None,
        description="Optional dataset ID associated with this study region"
    )


class StudyPlotResponse(BaseModel):
    """Persisted study region record returned from SQLite."""
    model_config = ConfigDict(extra="ignore")

    plot_id: str
    name: str
    is_active: bool
    geometry_type: str
    coordinates: List[Any]
    bbox: List[float]
    measurements: Dict[str, Any]
    dataset_id: Optional[str] = None
    created_at: str
    updated_at: str

